@startuml

@startuml
class MemberServiceImpl implements MemberService
class MemoryMemberRepository implements MemberRepository
class DbMemberRepository implements MemberRepository
interface MemberRepository

MemberServiceImpl --> MemberRepository


@enduml